/**
 * Centralized Phosphor icon barrel for the landing page.
 *
 * Pure re-exports of the server-rendered Phosphor icon set. No hooks, no
 * client-only behavior, so this file stays in the server tree and can be
 * imported by both Server Components and Client Components without
 * crossing the client boundary.
 *
 * One family only (Phosphor) is used across the marketing site. Stroke
 * weight and tone come from the global Tailwind theme tokens. Adding a
 * new icon used anywhere on the landing page requires adding it here
 * first so the import surface stays auditable.
 */

import {
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Books,
  Brain,
  CalendarBlank,
  ChatCircle,
  ChatCircleText,
  Check,
  CheckCircle,
  ClockCounterClockwise,
  Code,
  Command,
  Compass,
  Crosshair,
  Cube,
  Database,
  DownloadSimple,
  Fingerprint,
  Flame,
  Flask,
  FlowArrow,
  MathOperations,
  GitBranch,
  GitFork,
  GraduationCap,
  Infinity,
  Key,
  Lightning,
  List,
  ListChecks,
  LockSimple,
  MagnifyingGlass,
  Notebook,
  Notepad,
  Palette,
  PaperPlaneTilt,
  PencilLine,
  Plus,
  Pulse,
  Quotes,
  Repeat,
  Rocket,
  ShieldCheck,
  Sparkle,
  Stack,
  Target,
  Terminal,
  Timer,
  User,
  X,
} from "@phosphor-icons/react/dist/ssr";

export {
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Books,
  Brain,
  CalendarBlank,
  ChatCircle,
  ChatCircleText,
  Check,
  CheckCircle,
  ClockCounterClockwise,
  Code,
  Command,
  Compass,
  Crosshair,
  Cube,
  Database,
  DownloadSimple,
  Fingerprint,
  Flame,
  Flask,
  FlowArrow,
  MathOperations,
  GitBranch,
  GitFork,
  GraduationCap,
  Infinity,
  Key,
  Lightning,
  List,
  ListChecks,
  LockSimple,
  MagnifyingGlass,
  Notebook,
  Notepad,
  Palette,
  PaperPlaneTilt,
  PencilLine,
  Plus,
  Pulse,
  Quotes,
  Repeat,
  Rocket,
  ShieldCheck,
  Sparkle,
  Stack,
  Target,
  Terminal,
  Timer,
  User,
  X,
};

export type PhosphorIcon = typeof ArrowRight;
